/* Generated By:JavaCC: Do not edit this line. ScheduleParserConstants.java */
/*
 This file is part of SchedVis.

 SchedVis is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 SchedVis is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with SchedVis.  If not, see <http://www.gnu.org/licenses/>.

 */
package cz.muni.fi.spc.SchedVis.parsers.schedule;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface ScheduleParserConstants {

	/** End of File. */
	int EOF = 0;
	/** RegularExpression Id. */
	int CONSTANT = 1;
	/** RegularExpression Id. */
	int CONSTANT_LIST = 2;
	/** RegularExpression Id. */
	int DIGIT = 3;
	/** RegularExpression Id. */
	int STRING = 4;
	/** RegularExpression Id. */
	int WHITESPACE = 5;
	/** RegularExpression Id. */
	int MOVE_EVENT_FLAG = 6;
	/** RegularExpression Id. */
	int MACHINE_EVENT_FLAG = 7;
	/** RegularExpression Id. */
	int IO_EVENT_FLAG = 8;

	/** Lexical state. */
	int DEFAULT = 0;

	/** Literal token values. */
	String[] tokenImage = { "<EOF>", "<CONSTANT>", "<CONSTANT_LIST>", "<DIGIT>",
	    "<STRING>", "<WHITESPACE>", "<MOVE_EVENT_FLAG>", "<MACHINE_EVENT_FLAG>",
	    "<IO_EVENT_FLAG>", "\"\\n\"", "\"<\"", "\"|\"", "\">\"", "\";\"", };

}
