/* Generated By:JavaCC: Do not edit this line. MachinesParserConstants.java */
package cz.muni.fi.spc.SchedVis.parsers.machines;

public @SuppressWarnings("all") interface MachinesParserConstants {

  int EOF = 0;
  int CONSTANT = 1;
  int DIGIT = 2;
  int STRING = 3;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<CONSTANT>",
    "<DIGIT>",
    "<STRING>",
    "\"\\n\"",
    "\";\"",
  };

}
