/* Generated By:JavaCC: Do not edit this line. MachinesParserConstants.java */
package cz.muni.fi.spc.SchedVis.parsers.machines;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MachinesParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONSTANT = 1;
  /** RegularExpression Id. */
  int DIGIT = 2;
  /** RegularExpression Id. */
  int STRING = 3;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<CONSTANT>",
    "<DIGIT>",
    "<STRING>",
    "\"\\n\"",
    "\";\"",
  };

}
