/* Generated By:JavaCC: Do not edit this line. ScheduleParserConstants.java */
package cz.muni.fi.spc.SchedVis.parsers;

public interface ScheduleParserConstants {

  int EOF = 0;
  int CONSTANT = 1;
  int CONSTANT_LIST = 2;
  int DIGIT = 3;
  int STRING = 4;
  int WHITESPACE = 5;
  int MOVE_EVENT_FLAG = 6;
  int MACHINE_EVENT_FLAG = 7;
  int IO_EVENT_FLAG = 8;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<CONSTANT>",
    "<CONSTANT_LIST>",
    "<DIGIT>",
    "<STRING>",
    "<WHITESPACE>",
    "<MOVE_EVENT_FLAG>",
    "<MACHINE_EVENT_FLAG>",
    "<IO_EVENT_FLAG>",
    "\"\\n\"",
    "\"<\"",
    "\"|\"",
    "\">\"",
    "\";\"",
  };

}
